### ISSUE TITLE
Icons AND Arrows?

### ISSUE THREAD

**Issue by bobrocke** [buymeasoda/soda-theme#182]
I have ST3 build 3062 and Soda v2014.05.07.06.11.27.

I'm getting both the arrows, which I want AND the little folder icons, which I don't. Like this:

![icons](https://cloud.githubusercontent.com/assets/2962426/3211429/158d24d4-ef17-11e3-993e-13d5a6fdc03e.png)

How do I turn off the folder icons? `"soda_folder_icons": false,` doesn't do it.

**Comment by wunc** [comment]
I'm having the same problem in ST3 3083. @SergiiD 's solution in a User Theme customization file removes the arrow icons, but how would I do it the other way around (keep the arrows and remove the folder icons)?

**Comment by wunc** [comment]
Nevermind. Found it here: https://github.com/buymeasoda/soda-theme/issues/188#issuecomment-53908491

**Comment by pradyunsg** [comment]
@buymeasoda How about making the arrows a configurable option?

```json
[
    {
        "class": "disclosure_button_control",
        "settings": ["soda_hide_sidebar_arrows"],
        "content_margin": [0, 8]
    },
    {
        "class": "disclosure_button_control",
        "settings": ["!soda_hide_sidebar_arrows"],
        "content_margin": [8, 8]
    }
]
```
