### ISSUE TITLE
Error parsing plist xml:

### ISSUE THREAD

**Issue by charlesmudy** [buymeasoda/soda-theme#63]
I keep getting this errors:

Error loading colour scheme Packages/Theme - Soda/Soda Dark.sublime-theme: Error parsing plist xml: Error document empty. In file "Packages/Theme - Soda/Soda Dark.sublime-theme"

I have Sublime Text 2 Build 2181

**Comment by amjad-eshock** [comment]
Okay the problem is when you download the Zip file there is a sub-directory inside. All I did to resolve problem is copied everything inside the "soda-theme-master" and pasted the stuff in Theme - Soda directory and it worked fine. :-)
